{{- $ca := genCA "svc-cat-ca" 3650 }}
{{- $cn := "mutating-webhook" -}}
{{- $altName := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName) 3650 $ca }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-pod-cpu-booster
webhooks:
  - name: k8s-pod-cpu-booster.norbjd.github.io
    clientConfig:
      caBundle: {{ b64enc $ca.Cert }}
      service:
        namespace: {{ .Release.Namespace }}
        name: mutating-webhook
        path: /mutate
    objectSelector:
      matchExpressions:
        # we don't want that creation of mutating-webhook pods triggers the webhook (otherwise pods won't start)
        - key: app
          operator: NotIn
          values:
            - mutating-webhook
        - key: norbjd.github.io/k8s-pod-cpu-booster-enabled
          operator: In
          values:
            - "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE"]
        scope: Namespaced
    sideEffects: None
    admissionReviewVersions: ["v1"]
---
apiVersion: v1
kind: Secret
metadata:
  name: mutating-webhook-certs
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutating-webhook
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      app: mutating-webhook
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      containers:
        - name: mutating-webhook
          image: {{ .Values.webhook.image }}
          imagePullPolicy: {{ .Values.webhook.imagePullPolicy }}
          args:
            - -v=9
            - -port=8443
            - -cert=/etc/certs/tls.crt
            - -key=/etc/certs/tls.key
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: certs
              mountPath: /etc/certs
              readOnly: true
          resources:
            {{ toYaml .Values.resources }}
      volumes:
        - name: certs
          secret:
            secretName: mutating-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhook
spec:
  selector:
    app: mutating-webhook
  ports:
    - port: 443
      targetPort: 8443
