---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cpu-boost-reset
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-cpu-boost-reset
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-cpu-boost-reset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-cpu-boost-reset
subjects:
  - kind: ServiceAccount
    name: pod-cpu-boost-reset
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-cpu-boost-reset
spec:
  replicas: 1 # for now, we don't support multiple replicas
  selector:
    matchLabels:
      app: pod-cpu-boost-reset
  template:
    metadata:
      labels:
        app: pod-cpu-boost-reset
    spec:
      containers:
      - name: pod-cpu-boost-reset
        image: {{ .Values.informer.image }}
        imagePullPolicy: {{ .Values.informer.imagePullPolicy }}
        resources:
          {{ toYaml .Values.resources }}
      serviceAccountName: pod-cpu-boost-reset
      terminationGracePeriodSeconds: 0 # TODO: change for production environments
