apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: pod-cpu-booster
  name: pod-cpu-booster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-cpu-booster
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-cpu-booster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-cpu-booster
subjects:
- kind: ServiceAccount
  name: pod-cpu-booster
  namespace: pod-cpu-booster
