---
namespace: pod-cpu-booster
resources:
  - mutating-webhook.yaml
  - namespace.yaml
  - pod-cpu-boost-reset.yaml
secretGenerator:
  - name: mutating-webhook-certs
    options:
      disableNameSuffixHash: true
    type: kubernetes.io/tls
    files:
      - ca.crt
      - tls.crt
      - tls.key
replacements:
  - source:
      kind: Secret
      name: mutating-webhook-certs
      fieldPath: "data.[ca.crt]"
    targets:
      - select:
          kind: MutatingWebhookConfiguration
          name: k8s-pod-cpu-booster
        fieldPaths:
          - webhooks.[name=k8s-pod-cpu-booster.norbjd.github.io].clientConfig.caBundle
