apiVersion: v1
kind: Pod
metadata:
  name: pod-no-boost
spec:
  containers:
  - image: python:3.11-alpine
    name: python
    command: ["python"]
    args:
    - -m
    - http.server
    readinessProbe:
      tcpSocket:
        port: 8000
      initialDelaySeconds: 0
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 50m
        memory: 100M
      limits:
        cpu: 50m
        memory: 100M
  terminationGracePeriodSeconds: 0
