name: Release

on:
  push:
    branches:
    - main

jobs:
  release-container-images:
    name: build and push to ghcr.io
    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - uses: ko-build/setup-ko@v0.6
    - uses: actions/checkout@v4

    - name: Build and push
      env:
        KO_DOCKER_REPO: ghcr.io/norbjd/k8s-pod-cpu-booster
      run: |
        # something like 202403241909-abcdef01 if we want to use a specific version
        UNIQUE_TAG="$(TZ=UTC0 git log -1 --format=%cd --date=format-local:%Y%m%d%H%M)-$(git rev-parse --short HEAD)"

        ko build ./cmd/informer ./cmd/webhook \
          --base-import-paths \
          --sbom=none \
          --tags=$GITHUB_REF_NAME,$UNIQUE_TAG

  release-helm-chart:
    name: release helm chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
